"""全量表基线迁移（squash 自 4 条旧迁移，对齐数据模型文档 §2/§6）

链路：alembic upgrade head → 从当前 ORM 元数据一次性建全部表 → alembic check 零漂移。
背景：旧链路基线「存量表由 dev.db 承接」导致空库无法从零建表（batch_alter_table
      反射 sessions 即 NoSuchTableError），生产 PG 全新库不可用；上线前压平重建。
验证：SQLite 空库 upgrade head 通过；alembic check 无漂移；PG 方言 --sql 可编译。

Revision ID: 12cb8192e4f1
Revises:
Create Date: 2026-09-16 00:30:30.540402

"""

import sqlalchemy as sa

from alembic import op

revision = "12cb8192e4f1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=False),
        sa.Column("args", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("applicant", sa.String(length=64), nullable=False),
        sa.Column("approver", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_action"), "approvals", ["action"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(op.f("ix_approvals_tenant"), "approvals", ["tenant"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor"), "audit_logs", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant"), "audit_logs", ["tenant"], unique=False)
    op.create_table(
        "cost_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_records_session_id"), "cost_records", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_cost_records_tenant"), "cost_records", ["tenant"], unique=False)
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("vote", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedbacks_message_id"), "feedbacks", ["message_id"], unique=False)
    op.create_index(op.f("ix_feedbacks_session_id"), "feedbacks", ["session_id"], unique=False)
    op.create_index(op.f("ix_feedbacks_tenant"), "feedbacks", ["tenant"], unique=False)
    op.create_table(
        "kb_docs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("channels", sa.Text(), nullable=False),
        sa.Column("security_level", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "sha256", name="uq_kb_docs_tenant_sha"),
    )
    op.create_index(op.f("ix_kb_docs_sha256"), "kb_docs", ["sha256"], unique=False)
    op.create_index(op.f("ix_kb_docs_tenant"), "kb_docs", ["tenant"], unique=False)
    op.create_table(
        "members",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("user_ref", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "user_ref"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("spu_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("images", sa.Text(), nullable=False),
        sa.Column("attrs", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "spu_no", name="uq_product_spu"),
    )
    op.create_index(op.f("ix_products_tenant"), "products", ["tenant"], unique=False)
    op.create_table(
        "promos",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("budget", sa.Integer(), nullable=False),
        sa.Column("granted", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("per_user", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promos_status"), "promos", ["status"], unique=False)
    op.create_index(op.f("ix_promos_tenant"), "promos", ["tenant"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("outer_id", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.Column("replied", sa.Boolean(), nullable=False),
        sa.Column("reply", sa.Text(), nullable=False),
        sa.Column("ticket_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_level"), "reviews", ["level"], unique=False)
    op.create_index(op.f("ix_reviews_tenant"), "reviews", ["tenant"], unique=False)
    op.create_table(
        "sales_orders",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("outer_id", sa.String(length=64), nullable=False),
        sa.Column("items", sa.Text(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "platform", "outer_id", name="uq_order_outer"),
    )
    op.create_index(op.f("ix_sales_orders_status"), "sales_orders", ["status"], unique=False)
    op.create_index(op.f("ix_sales_orders_tenant"), "sales_orders", ["tenant"], unique=False)
    op.create_index(op.f("ix_sales_orders_trace_id"), "sales_orders", ["trace_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("handoff_status", sa.String(length=16), nullable=False),
        sa.Column("assignee", sa.String(length=64), nullable=False),
        sa.Column("handoff_reason", sa.String(length=200), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_handoff_status"), "sessions", ["handoff_status"], unique=False
    )
    op.create_index(op.f("ix_sessions_tenant"), "sessions", ["tenant"], unique=False)
    op.create_index(op.f("ix_sessions_username"), "sessions", ["username"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("checkpoint", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_tenant"), "tasks", ["tenant"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("plan", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quota_tokens", sa.Integer(), nullable=False),
        sa.Column("quota_concurrency", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_tenants_code"),
    )
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("assignee", sa.String(length=64), nullable=False),
        sa.Column("sla_due", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("conclusion", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_kind"), "tickets", ["kind"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_tenant"), "tickets", ["tenant"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("args", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_calls_name"), "tool_calls", ["name"], unique=False)
    op.create_index(op.f("ix_tool_calls_tenant"), "tool_calls", ["tenant"], unique=False)
    op.create_index(op.f("ix_tool_calls_trace_id"), "tool_calls", ["trace_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("pwd_hash", sa.String(length=256), nullable=False),
        sa.Column("roles", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "username", name="uq_users_tenant_username"),
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "name", name="uq_warehouse_name"),
    )
    op.create_index(op.f("ix_warehouses_tenant"), "warehouses", ["tenant"], unique=False)
    op.create_table(
        "aftersales",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("sales_order_id", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aftersales_sales_order_id"), "aftersales", ["sales_order_id"], unique=False
    )
    op.create_index(op.f("ix_aftersales_tenant"), "aftersales", ["tenant"], unique=False)
    op.create_index(op.f("ix_aftersales_trace_id"), "aftersales", ["trace_id"], unique=False)
    op.create_table(
        "coupon_grants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("promo_id", sa.String(length=32), nullable=False),
        sa.Column("user_ref", sa.String(length=64), nullable=False),
        sa.Column("order_ref", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idem_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "idem_key", name="uq_grants_tenant_idem"),
    )
    op.create_index(op.f("ix_coupon_grants_promo_id"), "coupon_grants", ["promo_id"], unique=False)
    op.create_index(op.f("ix_coupon_grants_tenant"), "coupon_grants", ["tenant"], unique=False)
    op.create_table(
        "kb_chunks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("doc_id", sa.String(length=32), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("vector_id", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["kb_docs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_chunks_doc_id"), "kb_chunks", ["doc_id"], unique=False)
    op.create_table(
        "logistics_orders",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("sales_order_id", sa.String(length=32), nullable=False),
        sa.Column("company", sa.String(length=40), nullable=False),
        sa.Column("tracking_no", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_logistics_orders_sales_order_id"),
        "logistics_orders",
        ["sales_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_logistics_orders_tenant"), "logistics_orders", ["tenant"], unique=False
    )
    op.create_index(
        op.f("ix_logistics_orders_tracking_no"), "logistics_orders", ["tracking_no"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachments", sa.Text(), nullable=False),
        sa.Column("citations", sa.Text(), nullable=False),
        sa.Column("guard", sa.Text(), nullable=False),
        sa.Column("faithfulness", sa.Float(), nullable=True),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("client_msg_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_client_msg_id"), "messages", ["client_msg_id"], unique=False)
    op.create_index(op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False)
    op.create_index(op.f("ix_messages_tenant"), "messages", ["tenant"], unique=False)
    op.create_index(op.f("ix_messages_trace_id"), "messages", ["trace_id"], unique=False)
    op.create_table(
        "session_notes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_notes_session_id"), "session_notes", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_session_notes_tenant"), "session_notes", ["tenant"], unique=False)
    op.create_table(
        "skus",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=32), nullable=False),
        sa.Column("color", sa.String(length=40), nullable=False),
        sa.Column("size", sa.String(length=20), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=False),
        sa.Column("list_price", sa.Integer(), nullable=False),
        sa.Column("sale_price", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "color", "size", name="uq_sku_variant"),
    )
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_index(op.f("ix_skus_tenant"), "skus", ["tenant"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.String(length=32), nullable=False),
        sa.Column("sku_id", sa.String(length=32), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Integer(), nullable=False),
        sa.Column("warn_line", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "sku_id", name="uq_inventory_row"),
    )
    op.create_index(op.f("ix_inventory_sku_id"), "inventory", ["sku_id"], unique=False)
    op.create_index(op.f("ix_inventory_tenant"), "inventory", ["tenant"], unique=False)
    op.create_index(op.f("ix_inventory_warehouse_id"), "inventory", ["warehouse_id"], unique=False)
    op.create_table(
        "stock_moves",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.String(length=32), nullable=False),
        sa.Column("sku_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("order_ref", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_moves_sku_id"), "stock_moves", ["sku_id"], unique=False)
    op.create_index(op.f("ix_stock_moves_tenant"), "stock_moves", ["tenant"], unique=False)
    op.create_index(
        op.f("ix_stock_moves_warehouse_id"), "stock_moves", ["warehouse_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_moves_warehouse_id"), table_name="stock_moves")
    op.drop_index(op.f("ix_stock_moves_tenant"), table_name="stock_moves")
    op.drop_index(op.f("ix_stock_moves_sku_id"), table_name="stock_moves")
    op.drop_table("stock_moves")
    op.drop_index(op.f("ix_inventory_warehouse_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_tenant"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_sku_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_skus_tenant"), table_name="skus")
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_table("skus")
    op.drop_index(op.f("ix_session_notes_tenant"), table_name="session_notes")
    op.drop_index(op.f("ix_session_notes_session_id"), table_name="session_notes")
    op.drop_table("session_notes")
    op.drop_index(op.f("ix_messages_trace_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_tenant"), table_name="messages")
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_client_msg_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_logistics_orders_tracking_no"), table_name="logistics_orders")
    op.drop_index(op.f("ix_logistics_orders_tenant"), table_name="logistics_orders")
    op.drop_index(op.f("ix_logistics_orders_sales_order_id"), table_name="logistics_orders")
    op.drop_table("logistics_orders")
    op.drop_index(op.f("ix_kb_chunks_doc_id"), table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_coupon_grants_tenant"), table_name="coupon_grants")
    op.drop_index(op.f("ix_coupon_grants_promo_id"), table_name="coupon_grants")
    op.drop_table("coupon_grants")
    op.drop_index(op.f("ix_aftersales_trace_id"), table_name="aftersales")
    op.drop_index(op.f("ix_aftersales_tenant"), table_name="aftersales")
    op.drop_index(op.f("ix_aftersales_sales_order_id"), table_name="aftersales")
    op.drop_table("aftersales")
    op.drop_index(op.f("ix_warehouses_tenant"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_table("users")
    op.drop_index(op.f("ix_tool_calls_trace_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tenant"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_name"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_tickets_tenant"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_kind"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_tasks_tenant"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_sessions_username"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_handoff_status"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_sales_orders_trace_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_tenant"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_status"), table_name="sales_orders")
    op.drop_table("sales_orders")
    op.drop_index(op.f("ix_reviews_tenant"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_level"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_promos_tenant"), table_name="promos")
    op.drop_index(op.f("ix_promos_status"), table_name="promos")
    op.drop_table("promos")
    op.drop_index(op.f("ix_products_tenant"), table_name="products")
    op.drop_table("products")
    op.drop_table("members")
    op.drop_index(op.f("ix_kb_docs_tenant"), table_name="kb_docs")
    op.drop_index(op.f("ix_kb_docs_sha256"), table_name="kb_docs")
    op.drop_table("kb_docs")
    op.drop_index(op.f("ix_feedbacks_tenant"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_session_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_message_id"), table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_cost_records_tenant"), table_name="cost_records")
    op.drop_index(op.f("ix_cost_records_session_id"), table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index(op.f("ix_audit_logs_tenant"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_approvals_tenant"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
