"""messages 加 client_msg_id（流式幂等键，对齐数据模型文档 §2）

链路：本修订 → ChatView 重连复用同一键不再插新行 → 验收“断网重连不重复消息”。
nullable=False 配 server_default=''，存量行零停机升级。

Revision ID: 6aea96793dc7
Revises: cb75c8ce8f15
Create Date: 2026-09-13 14:54:48.937850

"""

import sqlalchemy as sa

from alembic import op

revision = "6aea96793dc7"
down_revision = "cb75c8ce8f15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("client_msg_id", sa.String(length=64), nullable=False, server_default=""),
    )
    op.create_index(op.f("ix_messages_client_msg_id"), "messages", ["client_msg_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_client_msg_id"), table_name="messages")
    op.drop_column("messages", "client_msg_id")
    # ### end Alembic commands ###
