"""前置地基基线迁移（补 messages/tasks/tool_calls/kb_docs/kb_chunks/cost_records，对齐数据模型文档 §2）

链路：alembic upgrade head → 建 6 张地基表 → 各页面接真数据。
存量表（tenants/users/sessions 等）由既有 dev.db 承接，新库走 init_models() 全量建表兜底。

Revision ID: cb75c8ce8f15
Revises:
Create Date: 2026-09-13 14:02:44.929871

"""
import sqlalchemy as sa

from alembic import op

revision = 'cb75c8ce8f15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_records_session_id'), 'cost_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_cost_records_tenant'), 'cost_records', ['tenant'], unique=False)
    op.create_table('kb_docs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('security_level', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'sha256', name='uq_kb_docs_tenant_sha')
    )
    op.create_index(op.f('ix_kb_docs_sha256'), 'kb_docs', ['sha256'], unique=False)
    op.create_index(op.f('ix_kb_docs_tenant'), 'kb_docs', ['tenant'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_tenant'), 'tasks', ['tenant'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('args', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_name'), 'tool_calls', ['name'], unique=False)
    op.create_index(op.f('ix_tool_calls_tenant'), 'tool_calls', ['tenant'], unique=False)
    op.create_index(op.f('ix_tool_calls_trace_id'), 'tool_calls', ['trace_id'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.String(length=32), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['kb_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_chunks_doc_id'), 'kb_chunks', ['doc_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=False),
    sa.Column('guard', sa.Text(), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant'), 'messages', ['tenant'], unique=False)
    op.create_index(op.f('ix_messages_trace_id'), 'messages', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_trace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_kb_chunks_doc_id'), table_name='kb_chunks')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_tool_calls_trace_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_tenant'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_name'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_tasks_tenant'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_kb_docs_tenant'), table_name='kb_docs')
    op.drop_index(op.f('ix_kb_docs_sha256'), table_name='kb_docs')
    op.drop_table('kb_docs')
    op.drop_index(op.f('ix_cost_records_tenant'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_session_id'), table_name='cost_records')
    op.drop_table('cost_records')
    # ### end Alembic commands ###
